name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Build Docker image (optional)
      if: success()
      run: |
        docker build -t account-api:${{ github.run_number }} .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag account-api:${{ github.run_number }} ${{ secrets.DOCKER_REGISTRY }}/account-api:${{ github.run_number }}
        docker push ${{ secrets.DOCKER_REGISTRY }}/account-api:${{ github.run_number }}


