name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Build Docker image
      run: docker build -t mdahy911/account-api:${{ github.run_number }} .

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        if [ $? -eq 0 ]; then
          echo "Docker login successful."
        else
          echo "Docker login failed."
          exit 1
        fi

    - name: Push Docker image
      run: docker push mdahy911/account-api:${{ github.run_number }}
